name: LEGENDX RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP and Configure Firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "✅ RDP and Firewall Enabled."

      - name: Create LEGENDX User
        run: |
          $username = "legendxop"
          $password = "Ppssppgold1234#"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Remove-LocalUser -Name $username
          }
          New-LocalUser $username -Password $securePass -FullName "LEGENDX RDP"
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
          Write-Host "✅ User '$username' created."

      - name: Install Latest Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/S" -Wait
          Write-Host "✅ Latest Tailscale installed."

      - name: Connect to Tailscale
        id: ts
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname="gh-legendx"
          $tsIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
          echo "ts_ip=$tsIP" >> $env:GITHUB_OUTPUT
          Write-Host "✅ Tailscale connected with IP $tsIP"

      - name: Keep Runner Alive
        run: |
          Write-Host ""
          Write-Host "========== RDP SESSION ACTIVE =========="
          Write-Host "   IP Address: ${{ steps.ts.outputs.ts_ip }}"
          Write-Host "   Username:   legendxop"
          Write-Host "   Password:   Ppssppgold1234#"
          Write-Host "========================================"
          Write-Host ""
          Write-Host "This runner will stay alive for up to 6 hours."
          while ($true) {
            Start-Sleep -Seconds 60
          }
